{-
   Bitcoind
   The REST API can be enabled with the `-rest` option. The interface runs on the same port as the JSON-RPC interface, by default port `8332` for **mainnet**, port `18332` for **testnet**, and port `18443` for **regtest**.

   OpenAPI spec version: 0.16
   Contact: johan@lepetitbloc.net

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Request.Chain exposing (restChaininfo)

import Data.ChainInfo exposing (ChainInfo, chainInfoDecoder)
import Http
import Json.Decode as Decode


basePath : String
basePath =
    "http://localhost:3000/rest"


{-
   Returns various state info regarding block chain processing. Only supports JSON as output format.
-}
restChaininfo : Http.Request ChainInfo
restChaininfo =
    { method = "GET"
    , url = basePath ++ "/chaininfo.json"
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson chainInfoDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


