{-
   Bitcoind
   The REST API can be enabled with the `-rest` option. The interface runs on the same port as the JSON-RPC interface, by default port `8332` for **mainnet**, port `18332` for **testnet**, and port `18443` for **regtest**.

   OpenAPI spec version: 0.16
   Contact: johan@lepetitbloc.net

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Request.Transaction exposing (restTx)

import Data.Transaction exposing (Transaction, transactionDecoder)
import Http
import Json.Decode as Decode


basePath : String
basePath =
    "http://localhost:3000/rest"


{-
   Given a transaction hash: returns a transaction in binary, hex-encoded binary, or JSON formats. For full TX query capability, one must enable the transaction index via txindex&#x3D;1 command line / configuration option.
-}
restTx : String -> Http.Request Transaction
restTx txHash =
    { method = "GET"
    , url = basePath ++ "/tx/" ++ txHash
    , headers = []
    , body = Http.emptyBody
    , expect = Http.expectJson transactionDecoder
    , timeout = Just 30000
    , withCredentials = False
    }
        |> Http.request


