{-
   Bitcoind
   The REST API can be enabled with the `-rest` option. The interface runs on the same port as the JSON-RPC interface, by default port `8332` for **mainnet**, port `18332` for **testnet**, and port `18443` for **regtest**.

   OpenAPI spec version: 0.16
   Contact: johan@lepetitbloc.net

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.BIPReject exposing (BIPReject, bIPRejectDecoder, bIPRejectEncoder)

import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   the BIP rejection status
-}


type alias BIPReject =
    { status : Maybe Bool
    }


bIPRejectDecoder : Decoder BIPReject
bIPRejectDecoder =
    decode BIPReject
        |> optional "status" (Decode.nullable Decode.bool) Nothing



bIPRejectEncoder : BIPReject -> Encode.Value
bIPRejectEncoder model =
    Encode.object
        [ ( "status", withDefault Encode.null (map Encode.bool model.status) )
        ]


