{-
   Bitcoind
   The REST API can be enabled with the `-rest` option. The interface runs on the same port as the JSON-RPC interface, by default port `8332` for **mainnet**, port `18332` for **testnet**, and port `18443` for **regtest**.

   OpenAPI spec version: 0.16
   Contact: johan@lepetitbloc.net

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.ChainInfoBip9Softforks exposing (ChainInfoBip9Softforks, chainInfoBip9SoftforksDecoder, chainInfoBip9SoftforksEncoder)

import Data.BIP9 exposing (BIP9, bIP9Decoder, bIP9Encoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)


{-
   status of BIP9 softforks in progress
-}


type alias ChainInfoBip9Softforks =
    { name : Maybe BIP9
    }


chainInfoBip9SoftforksDecoder : Decoder ChainInfoBip9Softforks
chainInfoBip9SoftforksDecoder =
    decode ChainInfoBip9Softforks
        |> optional "name" (Decode.nullable bIP9Decoder) Nothing



chainInfoBip9SoftforksEncoder : ChainInfoBip9Softforks -> Encode.Value
chainInfoBip9SoftforksEncoder model =
    Encode.object
        [ ( "name", withDefault Encode.null (map bIP9Encoder model.name) )
        ]


