{-
   Bitcoind
   The REST API can be enabled with the `-rest` option. The interface runs on the same port as the JSON-RPC interface, by default port `8332` for **mainnet**, port `18332` for **testnet**, and port `18443` for **regtest**.

   OpenAPI spec version: 0.16
   Contact: johan@lepetitbloc.net

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.InlineResponseDefault exposing (InlineResponseDefault, inlineResponseDefaultDecoder, inlineResponseDefaultEncoder)

import Data.Transaction exposing (Transaction, transactionDecoder, transactionEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)




type alias InlineResponseDefault =
    { txid : Maybe Transaction
    }


inlineResponseDefaultDecoder : Decoder InlineResponseDefault
inlineResponseDefaultDecoder =
    decode InlineResponseDefault
        |> optional "txid" (Decode.nullable transactionDecoder) Nothing



inlineResponseDefaultEncoder : InlineResponseDefault -> Encode.Value
inlineResponseDefaultEncoder model =
    Encode.object
        [ ( "txid", withDefault Encode.null (map transactionEncoder model.txid) )
        ]


