{-
   Bitcoind
   The REST API can be enabled with the `-rest` option. The interface runs on the same port as the JSON-RPC interface, by default port `8332` for **mainnet**, port `18332` for **testnet**, and port `18443` for **regtest**.

   OpenAPI spec version: 0.16
   Contact: johan@lepetitbloc.net

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.InlineResponse200 exposing (InlineResponse200, inlineResponse200Decoder, inlineResponse200Encoder)

import Data.UTxO exposing (UTxO, uTxODecoder, uTxOEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)




type alias InlineResponse200 =
    { chainHeight : Maybe Int
    , chaintipHash : Maybe String
    , bitmap : Maybe String
    , utxos : Maybe (List UTxO)
    }


inlineResponse200Decoder : Decoder InlineResponse200
inlineResponse200Decoder =
    decode InlineResponse200
        |> optional "chainHeight" (Decode.nullable Decode.int) Nothing
        |> optional "chaintipHash" (Decode.nullable Decode.string) Nothing
        |> optional "bitmap" (Decode.nullable Decode.string) Nothing
        |> optional "utxos" (Decode.nullable (Decode.list uTxODecoder)) Nothing



inlineResponse200Encoder : InlineResponse200 -> Encode.Value
inlineResponse200Encoder model =
    Encode.object
        [ ( "chainHeight", withDefault Encode.null (map Encode.int model.chainHeight) )
        , ( "chaintipHash", withDefault Encode.null (map Encode.string model.chaintipHash) )
        , ( "bitmap", withDefault Encode.null (map Encode.string model.bitmap) )
        , ( "utxos", withDefault Encode.null (map (Encode.list << List.map uTxOEncoder) model.utxos) )
        ]


