{-
   Bitcoind
   The REST API can be enabled with the `-rest` option. The interface runs on the same port as the JSON-RPC interface, by default port `8332` for **mainnet**, port `18332` for **testnet**, and port `18443` for **regtest**.

   OpenAPI spec version: 0.16
   Contact: johan@lepetitbloc.net

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.MemoryPool exposing (MemoryPool, memoryPoolDecoder, memoryPoolEncoder)

import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)




type alias MemoryPool =
    { size : Maybe Int
    , bytes : Maybe Int
    , usage : Maybe Int
    , maxmempool : Maybe Int
    , mempoolminfee : Maybe Float
    , minrelaytxfee : Maybe Float
    }


memoryPoolDecoder : Decoder MemoryPool
memoryPoolDecoder =
    decode MemoryPool
        |> optional "size" (Decode.nullable Decode.int) Nothing
        |> optional "bytes" (Decode.nullable Decode.int) Nothing
        |> optional "usage" (Decode.nullable Decode.int) Nothing
        |> optional "maxmempool" (Decode.nullable Decode.int) Nothing
        |> optional "mempoolminfee" (Decode.nullable Decode.float) Nothing
        |> optional "minrelaytxfee" (Decode.nullable Decode.float) Nothing



memoryPoolEncoder : MemoryPool -> Encode.Value
memoryPoolEncoder model =
    Encode.object
        [ ( "size", withDefault Encode.null (map Encode.int model.size) )
        , ( "bytes", withDefault Encode.null (map Encode.int model.bytes) )
        , ( "usage", withDefault Encode.null (map Encode.int model.usage) )
        , ( "maxmempool", withDefault Encode.null (map Encode.int model.maxmempool) )
        , ( "mempoolminfee", withDefault Encode.null (map Encode.float model.mempoolminfee) )
        , ( "minrelaytxfee", withDefault Encode.null (map Encode.float model.minrelaytxfee) )
        ]


