{-
   Bitcoind
   The REST API can be enabled with the `-rest` option. The interface runs on the same port as the JSON-RPC interface, by default port `8332` for **mainnet**, port `18332` for **testnet**, and port `18443` for **regtest**.

   OpenAPI spec version: 0.16
   Contact: johan@lepetitbloc.net

   NOTE: This file is auto generated by the swagger code generator program.
   https://github.com/swagger-api/swagger-codegen.git
   Do not edit this file manually.
-}


module Data.UTxO exposing (UTxO, uTxODecoder, uTxOEncoder)

import Data.ScriptPubKey exposing (ScriptPubKey, scriptPubKeyDecoder, scriptPubKeyEncoder)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (decode, optional, required)
import Json.Encode as Encode
import Maybe exposing (map, withDefault)




type alias UTxO =
    { txvers : Maybe Int
    , height : Maybe Int
    , value : Maybe Float
    , scriptPubKey : Maybe ScriptPubKey
    }


uTxODecoder : Decoder UTxO
uTxODecoder =
    decode UTxO
        |> optional "txvers" (Decode.nullable Decode.int) Nothing
        |> optional "height" (Decode.nullable Decode.int) Nothing
        |> optional "value" (Decode.nullable Decode.float) Nothing
        |> optional "scriptPubKey" (Decode.nullable scriptPubKeyDecoder) Nothing



uTxOEncoder : UTxO -> Encode.Value
uTxOEncoder model =
    Encode.object
        [ ( "txvers", withDefault Encode.null (map Encode.int model.txvers) )
        , ( "height", withDefault Encode.null (map Encode.int model.height) )
        , ( "value", withDefault Encode.null (map Encode.float model.value) )
        , ( "scriptPubKey", withDefault Encode.null (map scriptPubKeyEncoder model.scriptPubKey) )
        ]


